# **Jupyter Notebook 1**

## **1. Introduction**

This notebook focuses on:

Selecting the dataset
Understanding its structure
Cleaning the data
Performing basic data wrangling

We are using the Iris dataset, a standard dataset widely used in machine learning and statistics.

**## 2. Data Selection**

**Dataset Description**

The Iris dataset contains measurements of iris flowers from three different species:

* Setosa
* Versicolor
* Virginica

**Features (Attributes)**
| Attribute Name | Description          | Data Type   |
| -------------- | -------------------- | ----------- |
| sepal_length   | Length of sepal (cm) | Float       |
| sepal_width    | Width of sepal (cm)  | Float       |
| petal_length   | Length of petal (cm) | Float       |
| petal_width    | Width of petal (cm)  | Float       |
| species        | Type of iris flower  | Categorical |


**3. Import Libraries**

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

**4. Load Dataset**

In [ ]:
# Load iris dataset from seaborn
df = sns.load_dataset('iris')

# Display first 5 rows
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

**5. Initial Data Inspection**

In [ ]:
# Shape of dataset
df.shape

# Data types
df.dtypes

# Summary statistics
df.describe()

# Check column names
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

**6. Data Understanding**

* Total rows: 150
* Total columns: 5
* All feature columns are numerical except species
* No immediate inconsistencies visible

**7. Checking Missing Values**

In [ ]:
# Check missing values
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

**Observation:**

No missing values found in dataset

**Conclusion**:

Dataset is clean with respect to missing data


**9. Data Filtering (Selection of Attributes)**

Reasoning:

For this project, we keep all attributes because:

* Each feature contributes to classification
* No irrelevant columns present

In [ ]:
# Selecting all relevant columns
df_filtered = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']]
df_filtered.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

**10. Data Type Validation**

In [ ]:
df_filtered.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

**Observation:**

* Numerical features are correctly stored as float
* Species is categorical (object type)

**11. Data Transformation**

In [ ]:
df_filtered['species'] = df_filtered['species'].astype('category')

In [ ]:
df_filtered.dtypes

sepal_length     float64
sepal_width      float64
petal_length     float64
petal_width      float64
species         category
dtype: object

# 12. Feature Renaming

In [ ]:
df_filtered.rename(columns={
    'sepal_length': 'SepalLength',
    'sepal_width': 'SepalWidth',
    'petal_length': 'PetalLength',
    'petal_width': 'PetalWidth',
    'species': 'Species'
}, inplace=True)

df_filtered.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth Species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

**13. Final Cleaned Dataset**

In [ ]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SepalLength  150 non-null    float64
 1   SepalWidth   150 non-null    float64
 2   PetalLength  150 non-null    float64
 3   PetalWidth   150 non-null    float64
 4   Species      150 non-null    category
dtypes: category(1), float64(4)
memory usage: 5.1 KB

**Final Observations:**
* Dataset is clean
* No missing values
* No duplicates
* Proper data types assigned
* Ready for EDA

**14. Save Cleaned Data**

In [ ]:
df_filtered.to_csv('iris_cleaned.csv', index=False)

**Conclusion**:
* The Iris dataset was selected due to its simplicity and suitability for classification tasks
* Data cleaning steps ensured:
  * No missing values
  * No duplicates
  * Correct data types

* The dataset is now ready for Exploratory Data Analysis (EDA) in Notebook 2